name: ballstatue_s2

####network#####
network: stage2
database_name: custom/ballstatue/1080
shader_config:
  sphere_direction: true
  human_light: false
apply_occ_loss: false
apply_std_loss: false
occ_loss_step: 20000
is_nerf: false
get_mask: true
zero_thickness: False

######loss######
loss: ['std','nerf_render']
val_metric: ['stage2']
key_metric_name: psnr
eikonal_weight: 0.05
freeze_inv_s_step: 15000

####dataset#####
train_dataset_type: dummy
dataset_dir: ./datasets
stage1_mesh_dir: ./data/meshes/ballstatue-300000_simplified.ply
stage1_ckpt_dir: ./data/model/ballstatue/model_best.pth
stage1_cfg_dir: ./configs/shape/real/ballstatue.yaml
train_dataset_cfg:
  database_name: custom/ballstatue/1080
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: custom/ballstatue/1080

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 150000
val_interval: 5000
save_interval: 1000
train_log_step: 20

downsample_ratio: 1.0