name: popcorncup_all_s2

####network#####
network: stage2
database_name: custom/popcorncup_all/1080
shader_config:
  sphere_direction: true
  human_light: false
apply_occ_loss: false
apply_std_loss: false
occ_loss_step: 10000
is_nerf: false
get_mask: true
zero_thickness: False

######loss######
loss: ['eikonal', 'nerf_render', 'std']
val_metric: [ 'stage2']
key_metric_name: psnr
eikonal_weight: 0.01
freeze_inv_s_step: 10000

####dataset#####
train_dataset_type: dummy
dataset_dir: ./datasets
stage1_mesh_dir: ./data/meshes/popcorncup_all_2-200000_simplified.ply
stage1_ckpt_dir: ./data/model/popcorncup_all_2/model.pth
stage1_cfg_dir: ./configs/shape/real/popcorncup.yaml
train_dataset_cfg:
  database_name: custom/popcorncup_all/1080
val_set_list:
  -
    name: val
    type: dummy
    cfg:
      database_name: custom/popcorncup_all/1080

####trainier####
optimizer_type: adam
lr_type: warm_up_cos
lr_cfg: {}
total_step: 150000
val_interval: 5000
save_interval: 1000
train_log_step: 20

downsample_ratio: 1.0
